#!/bin/bash

#echo "> Calculating for apache-ofbiz"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-ofbiz/ -o /home/kevin/Desktop/sac-data/gbab-apache-ofbiz/; echo "> Extracting for apache-ofbiz"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-ofbiz/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-ofbiz
#echo "> Calculating for mosync-ecplise"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/mosync-ecplise/ -o /home/kevin/Desktop/sac-data/gbab-mosync-ecplise/; echo "> Extracting for mosync-ecplise"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-mosync-ecplise/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-mosync-ecplise
#echo "> Calculating for opencv"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/opencv/ -o /home/kevin/Desktop/sac-data/gbab-opencv/; echo "> Extracting for opencv"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-opencv/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-opencv
#echo "> Calculating for spring-framework"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/spring-framework/ -o /home/kevin/Desktop/sac-data/gbab-spring-framework/; echo "> Extracting for spring-framework"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-spring-framework/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-spring-framework
#echo "> Calculating for apache-wicket"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-wicket/ -o /home/kevin/Desktop/sac-data/gbab-apache-wicket/; echo "> Extracting for apache-wicket"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-wicket/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-wicket
echo "> Calculating for apache-hbase"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-hbase/ -o /home/kevin/Desktop/sac-data/gbab-apache-hbase/; echo "> Extracting for apache-hbase"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-hbase/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-hbase
echo "> Calculating for apache-camel"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-camel/ -o /home/kevin/Desktop/sac-data/gbab-apache-camel/; echo "> Extracting for apache-camel"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-camel/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-camel
echo "> Calculating for apache-hadoop-hdfs"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-hadoop-hdfs/ -o /home/kevin/Desktop/sac-data/gbab-apache-hadoop-hdfs/; echo "> Extracting for apache-hadoop-hdfs"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-hadoop-hdfs/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-hadoop-hdfs
echo "> Calculating for apache-cassandra"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-cassandra/ -o /home/kevin/Desktop/sac-data/gbab-apache-cassandra/; echo "> Extracting for apache-cassandra"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-cassandra/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-cassandra
#echo "> Calculating for apache-felix"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-felix/ -o /home/kevin/Desktop/sac-data/gbab-apache-felix/; echo "> Extracting for apache-felix"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-felix/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-felix
#echo "> Calculating for apache-flume"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-flume/ -o /home/kevin/Desktop/sac-data/gbab-apache-flume/; echo "> Extracting for apache-flume"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-flume/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-flume
#echo "> Calculating for apache-hadoop"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-hadoop/ -o /home/kevin/Desktop/sac-data/gbab-apache-hadoop/; echo "> Extracting for apache-hadoop"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-hadoop/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-hadoop