#!/bin/bash

echo "> Calculating for bnd-tools"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/bnd-tools/ -o /home/kevin/Desktop/sac-data/gbab-bnd-tools/; echo "> Extracting for bnd-tools"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-bnd-tools/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-bnd-tools
echo "> Calculating for ceylon-eclipse"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/ceylon-eclipse/ -o /home/kevin/Desktop/sac-data/gbab-ceylon-eclipse/; echo "> Extracting for ceylon-eclipse"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-ceylon-eclipse/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-ceylon-eclipse
echo "> Calculating for facebook-android-sdk"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/facebook-android-sdk/ -o /home/kevin/Desktop/sac-data/gbab-facebook-android-sdk/; echo "> Extracting for facebook-android-sdk"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-facebook-android-sdk/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-facebook-android-sdk
echo "> Calculating for github-android"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/github-android/ -o /home/kevin/Desktop/sac-data/gbab-github-android/; echo "> Extracting for github-android"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-github-android/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-github-android
echo "> Calculating for groovy-eclipse"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/groovy-eclipse/ -o /home/kevin/Desktop/sac-data/gbab-groovy-eclipse/; echo "> Extracting for groovy-eclipse"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-groovy-eclipse/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-groovy-eclipse
echo "> Calculating for mongodb"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/mongodb/ -o /home/kevin/Desktop/sac-data/gbab-mongodb/; echo "> Extracting for mongodb"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-mongodb/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-mongodb
echo "> Calculating for mosync-ecplise"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/mosync-ecplise/ -o /home/kevin/Desktop/sac-data/gbab-mosync-ecplise/; echo "> Extracting for mosync-ecplise"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-mosync-ecplise/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-mosync-ecplise
echo "> Calculating for opencv"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/opencv/ -o /home/kevin/Desktop/sac-data/gbab-opencv/; echo "> Extracting for opencv"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-opencv/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-opencv
echo "> Calculating for spring-framework"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/spring-framework/ -o /home/kevin/Desktop/sac-data/gbab-spring-framework/; echo "> Extracting for spring-framework"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-spring-framework/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-spring-framework
echo "> Calculating for vrapper"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/vrapper/ -o /home/kevin/Desktop/sac-data/gbab-vrapper/; echo "> Extracting for vrapper"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-vrapper/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-vrapper
