#!/bin/bash

echo "> Calculating for apache-mina"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-mina/ -o /home/kevin/Desktop/sac-data/gbab-apache-mina/; echo "> Extracting for apache-mina"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-mina/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-mina
echo "> Calculating for apache-ofbiz"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-ofbiz/ -o /home/kevin/Desktop/sac-data/gbab-apache-ofbiz/; echo "> Extracting for apache-ofbiz"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-ofbiz/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-ofbiz
echo "> Calculating for apache-pig"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-pig/ -o /home/kevin/Desktop/sac-data/gbab-apache-pig/; echo "> Extracting for apache-pig"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-pig/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-pig
echo "> Calculating for apache-shindig"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-shindig/ -o /home/kevin/Desktop/sac-data/gbab-apache-shindig/; echo "> Extracting for apache-shindig"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-shindig/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-shindig
echo "> Calculating for apache-struts2"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-struts2/ -o /home/kevin/Desktop/sac-data/gbab-apache-struts2/; echo "> Extracting for apache-struts2"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-struts2/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-struts2
echo "> Calculating for apache-tika"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-tika/ -o /home/kevin/Desktop/sac-data/gbab-apache-tika/; echo "> Extracting for apache-tika"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-tika/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-tika
echo "> Calculating for apache-tomcat"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-tomcat/ -o /home/kevin/Desktop/sac-data/gbab-apache-tomcat/; echo "> Extracting for apache-tomcat"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-tomcat/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-tomcat
echo "> Calculating for apache-traffic-server"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-traffic-server/ -o /home/kevin/Desktop/sac-data/gbab-apache-traffic-server/; echo "> Extracting for apache-traffic-server"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-traffic-server/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-traffic-server
echo "> Calculating for apache-wicket"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-wicket/ -o /home/kevin/Desktop/sac-data/gbab-apache-wicket/; echo "> Extracting for apache-wicket"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-wicket/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-wicket
echo "> Calculating for apache-zookeeper"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-zookeeper/ -o /home/kevin/Desktop/sac-data/gbab-apache-zookeeper/; echo "> Extracting for apache-zookeeper"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-zookeeper/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-zookeeper
