#!/bin/bash

echo "> Calculating for apache-activemq"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-activemq/ -o /home/kevin/Desktop/sac-data/gbab-apache-activemq/; echo "> Extracting for apache-activemq"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-activemq/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-activemq
echo "> Calculating for apache-avro"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-avro/ -o /home/kevin/Desktop/sac-data/gbab-apache-avro/; echo "> Extracting for apache-avro"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-avro/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-avro
echo "> Calculating for apache-camel"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-camel/ -o /home/kevin/Desktop/sac-data/gbab-apache-camel/; echo "> Extracting for apache-camel"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-camel/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-camel
echo "> Calculating for apache-cassandra"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-cassandra/ -o /home/kevin/Desktop/sac-data/gbab-apache-cassandra/; echo "> Extracting for apache-cassandra"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-cassandra/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-cassandra
echo "> Calculating for apache-felix"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-felix/ -o /home/kevin/Desktop/sac-data/gbab-apache-felix/; echo "> Extracting for apache-felix"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-felix/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-felix
echo "> Calculating for apache-flume"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-flume/ -o /home/kevin/Desktop/sac-data/gbab-apache-flume/; echo "> Extracting for apache-flume"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-flume/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-flume
echo "> Calculating for apache-hadoop"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-hadoop/ -o /home/kevin/Desktop/sac-data/gbab-apache-hadoop/; echo "> Extracting for apache-hadoop"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-hadoop/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-hadoop
echo "> Calculating for apache-hadoop-hdfs"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-hadoop-hdfs/ -o /home/kevin/Desktop/sac-data/gbab-apache-hadoop-hdfs/; echo "> Extracting for apache-hadoop-hdfs"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-hadoop-hdfs/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-hadoop-hdfs
echo "> Calculating for apache-hbase"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-hbase/ -o /home/kevin/Desktop/sac-data/gbab-apache-hbase/; echo "> Extracting for apache-hbase"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-hbase/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-hbase
echo "> Calculating for apache-mahout"; python3 /home/kevin/Documents/git_by_a_bus/git_by_a_bus.py /home/kevin/Desktop/repos/apache-mahout/ -o /home/kevin/Desktop/sac-data/gbab-apache-mahout/; echo "> Extracting for apache-mahout"; python3 get_top_contrib_per_file.py /home/kevin/Desktop/sac-data/gbab-apache-mahout/estimate_unique_knowledge.tsv /home/kevin/Desktop/sac-data/contrib-apache-mahout
