#!/bin/sh

git clone https://github.com/github/android.git github-android
git clone https://github.com/spring-projects/spring-framework.git spring-framework
git clone https://github.com/vrapper/vrapper.git vrapper
git clone https://github.com/MoSync/Eclipse.git mosync-ecplise
git clone https://github.com/ceylon/ceylon-ide-eclipse.git ceylon-eclipse
git clone https://github.com/groovy/groovy-eclipse.git groovy-eclipse
git clone https://github.com/bndtools/bndtools.git bnd-tools
git clone git://git.apache.org/cassandra.git apache-cassandra
git clone git://git.apache.org/hadoop-common.git apache-hadoop
git clone git://git.apache.org/mahout.git apache-mahout
git clone git://git.apache.org/hbase.git apache-hbase
git clone git://git.apache.org/zookeeper.git apache-zookeeper
git clone git://git.apache.org/pig.git apache-pig
git clone git://git.apache.org/avro.git apache-avro
git clone git://git.apache.org/wicket.git apache-wicket
git clone git://git.apache.org/camel.git apache-camel
git clone git://git.apache.org/flume.git apache-flume
git clone git://git.apache.org/hadoop-hdfs.git apache-hadoop-hdfs
git clone https://github.com/lbroman/struts2.git apache-struts2
git clone git://git.apache.org/tomcat.git apache-tomcat
git clone git://git.apache.org/activemq.git apache-activemq
git clone git://git.apache.org/tika.git apache-tika
git clone git://git.apache.org/trafficserver.git apache-traffic-server
git clone git://git.apache.org/felix.git apache-felix
git clone git://git.apache.org/shindig.git apache-shindig
git clone git://git.apache.org/ofbiz.git apache-ofbiz
git clone git://git.apache.org/mina.git apache-mina
git clone https://github.com/facebook/facebook-android-sdk.git facebook-android-sdk
git clone https://github.com/Itseez/opencv.git opencv
git clone https://github.com/doctrine/mongodb.git mongodb