#!/bin/bash

echo "> Calculating for apache-activemq"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-activemq/ /home/kevin/Desktop/sac-data/bug-commit-apache-activemq/
echo "> Calculating for apache-avro"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-avro/ /home/kevin/Desktop/sac-data/bug-commit-apache-avro/
echo "> Calculating for apache-camel"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-camel/ /home/kevin/Desktop/sac-data/bug-commit-apache-camel/
echo "> Calculating for apache-cassandra"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-cassandra/ /home/kevin/Desktop/sac-data/bug-commit-apache-cassandra/
echo "> Calculating for apache-felix"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-felix/ /home/kevin/Desktop/sac-data/bug-commit-apache-felix/
echo "> Calculating for apache-flume"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-flume/ /home/kevin/Desktop/sac-data/bug-commit-apache-flume/
echo "> Calculating for apache-hadoop"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-hadoop/ /home/kevin/Desktop/sac-data/bug-commit-apache-hadoop/
echo "> Calculating for apache-hadoop-hdfs"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-hadoop-hdfs/ /home/kevin/Desktop/sac-data/bug-commit-apache-hadoop-hdfs/
echo "> Calculating for apache-hbase"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-hbase/ /home/kevin/Desktop/sac-data/bug-commit-apache-hbase/
echo "> Calculating for apache-mahout"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-mahout/ /home/kevin/Desktop/sac-data/bug-commit-apache-mahout/
echo "> Calculating for apache-mina"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-mina/ /home/kevin/Desktop/sac-data/bug-commit-apache-mina/
echo "> Calculating for apache-ofbiz"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-ofbiz/ /home/kevin/Desktop/sac-data/bug-commit-apache-ofbiz/
echo "> Calculating for apache-pig"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-pig/ /home/kevin/Desktop/sac-data/bug-commit-apache-pig/
echo "> Calculating for apache-shindig"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-shindig/ /home/kevin/Desktop/sac-data/bug-commit-apache-shindig/
echo "> Calculating for apache-struts2"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-struts2/ /home/kevin/Desktop/sac-data/bug-commit-apache-struts2/
echo "> Calculating for apache-tika"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-tika/ /home/kevin/Desktop/sac-data/bug-commit-apache-tika/
echo "> Calculating for apache-tomcat"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-tomcat/ /home/kevin/Desktop/sac-data/bug-commit-apache-tomcat/
echo "> Calculating for apache-traffic-server"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-traffic-server/ /home/kevin/Desktop/sac-data/bug-commit-apache-traffic-server/
echo "> Calculating for apache-wicket"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-wicket/ /home/kevin/Desktop/sac-data/bug-commit-apache-wicket/
echo "> Calculating for apache-zookeeper"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/apache-zookeeper/ /home/kevin/Desktop/sac-data/bug-commit-apache-zookeeper/
echo "> Calculating for bnd-tools"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/bnd-tools/ /home/kevin/Desktop/sac-data/bug-commit-bnd-tools/
echo "> Calculating for ceylon-eclipse"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/ceylon-eclipse/ /home/kevin/Desktop/sac-data/bug-commit-ceylon-eclipse/
echo "> Calculating for facebook-android-sdk"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/facebook-android-sdk/ /home/kevin/Desktop/sac-data/bug-commit-facebook-android-sdk/
echo "> Calculating for github-android"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/github-android/ /home/kevin/Desktop/sac-data/bug-commit-github-android/
echo "> Calculating for groovy-eclipse"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/groovy-eclipse/ /home/kevin/Desktop/sac-data/bug-commit-groovy-eclipse/
echo "> Calculating for mongodb"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/mongodb/ /home/kevin/Desktop/sac-data/bug-commit-mongodb/
echo "> Calculating for mosync-ecplise"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/mosync-ecplise/ /home/kevin/Desktop/sac-data/bug-commit-mosync-ecplise/
echo "> Calculating for opencv"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/opencv/ /home/kevin/Desktop/sac-data/bug-commit-opencv/
echo "> Calculating for spring-framework"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/spring-framework/ /home/kevin/Desktop/sac-data/bug-commit-spring-framework/
echo "> Calculating for vrapper"; python3 get_bug_commit_ratio_per_file.py /home/kevin/Desktop/repos/vrapper/ /home/kevin/Desktop/sac-data/bug-commit-vrapper/
